"""empty message

Revision ID: 0c0186e5116a
Revises: 83c890ec5a03
Create Date: 2024-05-23 19:23:00.040016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import fastapi_storages


# revision identifiers, used by Alembic.
revision: str = '0c0186e5116a'
down_revision: Union[str, None] = '83c890ec5a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarjimalar',
    sa.Column('object_type', sa.Unicode(length=255), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('category', 'name_translations')
    op.drop_column('category', 'locale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('locale', sa.VARCHAR(), nullable=True))
    op.add_column('category', sa.Column('name_translations', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('category', 'name')
    op.drop_table('tarjimalar')
    # ### end Alembic commands ###
