"""empty message

Revision ID: 3ae81f85d07b
Revises: 
Create Date: 2024-08-25 17:30:34.187157

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# import sqlalchemy_file
# import fastapi_storages


# revision identifiers, used by Alembic.
revision: str = '3ae81f85d07b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tg_users',
                    sa.Column('firstname', sa.String(
                        length=63), nullable=True),
                    sa.Column('lastname', sa.String(length=63), nullable=True),
                    sa.Column('username', sa.String(length=63), nullable=True),
                    sa.Column('phone_number', sa.String(
                        length=15), nullable=True),
                    sa.Column('tg_user_id', sa.String(
                        length=15), nullable=True),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('firstname', sa.String(
                        length=63), nullable=True),
                    sa.Column('lastname', sa.String(length=63), nullable=True),
                    sa.Column('username', sa.String(length=63), nullable=True),
                    sa.Column('password', sa.String(length=63), nullable=True),
                    sa.Column('phone_number', sa.String(
                        length=15), nullable=True),
                    sa.Column('tg_user_id', sa.String(
                        length=15), nullable=True),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tg_users')
    op.drop_table('products')
    # ### end Alembic commands ###
