"""empty message

Revision ID: 48bbb2e592c6
Revises: 6e0c5ae9399b
Create Date: 2024-04-22 13:31:26.573164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48bbb2e592c6'
down_revision: Union[str, None] = '6e0c5ae9399b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_ibfk_1', 'books', type_='foreignkey')
    op.drop_constraint('books_ibfk_2', 'books', type_='foreignkey')
    op.drop_column('books', 'file')
    op.drop_column('books', 'audio_file')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'subcategry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('subcategry_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('audio_file', mysql.VARCHAR(length=63), nullable=True))
    op.add_column('books', sa.Column('file', mysql.VARCHAR(length=63), nullable=True))
    op.create_foreign_key('books_ibfk_2', 'books', 'subcategory', ['subcategry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('books_ibfk_1', 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
