"""empty message

Revision ID: 83c890ec5a03
Revises: 42966e76a3d5
Create Date: 2024-05-23 19:03:33.409117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file
import fastapi_storages


# revision identifiers, used by Alembic.
revision: str = '83c890ec5a03'
down_revision: Union[str, None] = '42966e76a3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name_translations', sa.String(length=255), nullable=True))
    op.add_column('category', sa.Column('locale', sa.String(), nullable=True))
    op.drop_column('category', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('category', 'locale')
    op.drop_column('category', 'name_translations')
    # ### end Alembic commands ###
