"""empty message

Revision ID: cf56a15e0179
Revises: 48bbb2e592c6
Create Date: 2024-05-11 11:55:39.518825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf56a15e0179'
down_revision: Union[str, None] = '48bbb2e592c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.add_column('category', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('lft', sa.Integer(), nullable=False))
    op.add_column('category', sa.Column('rgt', sa.Integer(), nullable=False))
    op.add_column('category', sa.Column('level', sa.Integer(), nullable=False))
    op.create_index('category_level_idx', 'category', ['level'], unique=False)
    op.create_index('category_lft_idx', 'category', ['lft'], unique=False)
    op.create_index('category_rgt_idx', 'category', ['rgt'], unique=False)
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_index('category_rgt_idx', table_name='category')
    op.drop_index('category_lft_idx', table_name='category')
    op.drop_index('category_level_idx', table_name='category')
    op.drop_column('category', 'level')
    op.drop_column('category', 'rgt')
    op.drop_column('category', 'lft')
    op.drop_column('category', 'parent_id')
    op.drop_column('category', 'tree_id')
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=127), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
